package ngo.friendship.satellite.constants
// TODO: Auto-generated Javadoc
/**
 * The Class QuestionnaireName.
 */
object QuestionnaireName {
    const val BENEFICIARY_REGISTRATION = "BENEFICIARY_REGISTRATION"
    const val CERVICAL_CANCER_SCREENING = "CERVICAL_CANCER_SCREENING"
    const val CERVICAL_CANCER_FOLLOWUP = "CERVICAL_CANCER_FOLLOWUP"
    const val CERVICAL_CANCER = "CERVICAL_CANCER"
    const val EPI = "EPI"
    const val EPI_FOLLOWUP = "EPI_FOLLOWUP"
    const val EPI_BENEF_LIST = "EPI_BENEF_LIST"
    const val MATERNAL_BENEF_LIST = "MATERNAL_BENEF_LIST"
    const val CHILD_BENEF_LIST = "CHILD_BENEF_LIST"
    const val TT = "TT"
    const val TT_FOLLOWUP = "TT_FOLLOWUP"
    const val TT_BENEF_LIST = "TT_BENEF_LIST"
    const val CHILD_GROWTH_ASSESSMENT = "CHILD_GROWTH_ASSESSMENT"
    const val HOUSEHOLD_LIST = "HOUSEHOLD_LIST"
    const val HOUSEHOLD_REGISTRATION = "HOUSEHOLD_REGISTRATION"
    const val BENEFICIARY_PROFILE_UPDATE = "BENEFICIARY_PROFILE_UPDATE"
    const val MATERNAL_PREGNANT_MOTHER_REGISTRATION = "MATERNAL_PREGNANT_MOTHER_REGISTRATION"
    const val MATERNAL_MOTHER_AND_BABY_REGISTRATION = "MATERNAL_MOTHER_AND_BABY_REGISTRATION"
    const val MATERNAL_HIGH_RISK_MOTHER_IDENTIFICATION = "MATERNAL_HIGH_RISK_MOTHER_IDENTIFICATION"
    const val MATERNAL_DELIVERY_CARE = "MATERNAL_DELIVERY_CARE"
    const val MATERNAL_DISCONTINUATION_OF_PREGNANCY = "MATERNAL_DISCONTINUATION_OF_PREGNANCY"
    const val BENEFICIARY_MIGRATION = "BENEFICIARY_MIGRATION"
    const val DEATH_REGISTRATION = "DEATH_REGISTRATION"
    const val COURT_YARD = "COURT_YARD"
    const val DIABETES_BENEF_LIST = "DIABETES_BENEF_LIST"
    const val DIABETES_SCREENING = "DIABETES_SCREENING"
    const val HYPERTENSION_SCREENING = "HYPERTENSION_SCREENING"
    const val HYPERTENSION_BENEF_LIST = "HYPERTENSION_BENEF_LIST"
}